# .github/workflows/build_fasttext_concurrent.yml
name: Build fastText for Windows (multiple Python versions)

on:
  workflow_dispatch:

jobs:
  build_windows_wheels:
    name: Build fastText on Windows (Python ${{ matrix.python-version }}, 64-bit)
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13'] # 尝试 3.12 和 3.13

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 基础 Python 版本

    - name: Install cibuildwheel
      run: pip install cibuildwheel==2.20.0

    - name: Build fastText wheels for Windows (Python ${{ matrix.python-version }})
      run: python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_PLATFORM: windows
        CIBW_BUILD: cp${{ matrix.python-version }}* # 使用矩阵变量
        CIBW_ARCHS_WINDOWS: AMD64
        CIBW_BEFORE_BUILD: pip install cython
        CIBW_PRERELEASE_PYTHONS: 'True'
        CIBW_BUILD_VERBOSITY: '3' # 详细日志

    - name: Upload Windows Python wheels
      uses: actions/upload-artifact@v4
      with:
        name: fasttext-wheels-windows-py${{ matrix.python-version }}
        path: wheelhouse/*.whl


