# .github/workflows/build.yml
name: Build fastText for Windows (CPython 3.12/3.13)

on:
  workflow_dispatch:

jobs:
  build_windows_wheels:
    name: Build fastText on Windows (cibw tag: ${{ matrix.cibw_tag }})
    runs-on: windows-latest
    strategy:
      matrix:
        cibw_tag: ['cp312-*', 'cp313-*']

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # cibuildwheel 自己会下载 3.12/3.13

      - name: Install cibuildwheel
        run: pip install cibuildwheel==2.20.0

      - name: Build fastText wheels for Windows (${{ matrix.cibw_tag }})
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_PLATFORM: windows
          CIBW_BUILD: ${{ matrix.cibw_tag }}
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_PRERELEASE_PYTHONS: 'True'     # 允许 3.13 预发布
          CIBW_BUILD_VERBOSITY: '3'

          # 在构建前升级工具并安装依赖；并打印 CL 以确认生效
          CIBW_BEFORE_BUILD_WINDOWS: >
            echo ==== CL BEFORE ==== &
            set CL &
            echo ==================== &
            pip install -U pip setuptools wheel &
            pip install -U "pybind11>=2.12" cython

          # 关键：给 MSVC 传 C++17 等编译参数（不要加整体引号）
          CIBW_ENVIRONMENT_WINDOWS: |
            CL=/std:c++17 /EHsc /openmp /Zc:__cplusplus

      - name: Upload Windows Python wheels
        uses: actions/upload-artifact@v4
        with:
          name: fasttext-wheels-${{ matrix.cibw_tag }}
          path: wheelhouse/*.whl


